version: "3.5"

services:
  fedora-latest:
    build:
      context: .
      dockerfile: dockerfiles/fedora-latest.dockerfile
    volumes:
      - .:/source:delegated
    command:
      /source/dockerfiles/run-test.sh
